name: voxpollui
description: Voxpoll ui
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  parse_server_sdk_flutter: ^7.0.0
  flutter:
    sdk: flutter
  flutter_polls: ^0.1.3
  flutter_dotenv: ^5.1.0 
  provider: ^6.1.1 # global veri aktarımı anlık değişimler (dark mode, light mode)
  shared_preferences: ^2.2.2 # önbellek pakedi
  image_picker: ^1.0.7 # galeri pakedi 
  table_calendar: ^3.0.9 # Takvim oluşturucu
  shimmer: ^3.0.0 # yükleme ekranı için
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  flutter_localization: ^0.2.2
  better_polls: ^1.0.8
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/Logo.png" # İkon dosyasının yolu
# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - .env.sample
    - assets/image/login.png
    - assets/image/onboard1.png
    - assets/image/onboard2.png
    - assets/image/onboard3.png
    - assets/image/onboard4.png
    - assets/image/cover.png
    - assets/image/profilepicture.png
    - assets/image/profil_foto1.png
    - assets/image/profil_foto2.png
    - assets/image/profil_foto3.png
    - assets/image/Done.png
    - assets/image/Logo.png
    - assets/image/cal.svg
    - assets/image/settings_image.svg
    - assets/image/setting.svg
    - assets/image/ibrahim.png
    - assets/image/add_image.svg
    - assets/image/anket_iko.png

    - assets/image/bottom_navigation/community.svg
    - assets/image/bottom_navigation/community_selected.svg
    - assets/image/bottom_navigation/groups.svg
    - assets/image/bottom_navigation/group_selected.svg
    - assets/image/bottom_navigation/home_selected.svg
    - assets/image/bottom_navigation/home.svg
    - assets/image/bottom_navigation/person.svg
    - assets/image/bottom_navigation/person_selected.svg
    - assets/image/bottom_navigation/home_png.png
    - assets/image/bottom_navigation/home_selected_png.png
    - assets/image/bottom_navigation/person_png.png
    - assets/image/bottom_navigation/person_selected_png.png

    - assets/image/bottom_sheet_menu/png/paylas.png
    - assets/image/bottom_sheet_menu/png/takip_birak.png
    - assets/image/bottom_sheet_menu/png/bildir.png
    - assets/image/bottom_sheet_menu/png/engel.png
    - assets/image/bottom_sheet_menu/png/sessize_al.png
    - assets/image/bottom_sheet_menu/png/sikayet.png

    - assets/image/bottom_sheet_menu/paylas.svg
    - assets/image/bottom_sheet_menu/takip_birak.svg
    - assets/image/bottom_sheet_menu/bildir.svg
    - assets/image/bottom_sheet_menu/engel.svg
    - assets/image/bottom_sheet_menu/sessize_al.svg
    - assets/image/bottom_sheet_menu/sikayet.svg


    - assets/image/profile_community/1453.png
    - assets/image/profile_community/baydoner.png
    - assets/image/profile_community/beymen.png
    - assets/image/profile_community/cinema.png
    - assets/image/profile_community/gofrette_profile.png
    - assets/image/profile_community/karen.png
    - assets/image/profile_community/backk.png


    - assets/image/profile_community/1453.svg
    - assets/image/profile_community/baydoner.svg
    - assets/image/profile_community/beymen.svg
    - assets/image/profile_community/cinema.svg
    - assets/image/profile_community/gofrette.svg
    - assets/image/profile_community/karen.svg



  fonts:
   - family: Gilroy
     fonts:
       - asset: assets/fonts/gilroy/Gilroy-Black.ttf
   - family: Gilroy-light
     fonts: 
       - asset: assets/fonts/gilroy/Gilroy-Light.ttf
   - family: Gilroy-medium
     fonts:
       - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
   - family: Gilroy-bold
     fonts:
       - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
   - family: Gilroy-heavhy
     fonts:
       - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
   - family: Gilroy-regular
     fonts:
       - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
   - family: Gilroy-semibold
     fonts:
       - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
