name: voxpollui
description: Voxpoll ui
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #core
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  go_router: ^14.2.1
  equatable: ^2.0.5
  easy_localization: ^3.0.7
  collection: ^1.18.0
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  #firebase
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  firebase_storage: ^12.3.1
  cloud_firestore: ^5.4.1
  #ui
  shimmer: ^3.0.0
  stylish_bottom_bar: ^1.1.0
  flutter_svg: ^2.0.9
  pinput: ^5.0.0
  skeletonizer: ^1.4.2
  animated_custom_dropdown: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  go_router_builder: ^2.3.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/image/
    - assets/image/bottom_nav_bar/
    - assets/image/bottom_sheet_menu/
    - assets/image/common/
    - assets/image/onboard/


  fonts:
  - family: Gilroy
    fonts:
    - asset: assets/fonts/gilroy/Gilroy-Black.ttf
  - family: Gilroy-light
    fonts: 
    - asset: assets/fonts/gilroy/Gilroy-Light.ttf
  - family: Gilroy-medium
    fonts:
    - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
  - family: Gilroy-bold
    fonts:
    - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
  - family: Gilroy-heavhy
    fonts:
    - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
  - family: Gilroy-regular
    fonts:
    - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
  - family: Gilroy-semibold
    fonts:
    - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
